/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Abstract.User;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author harshalneelkamal
 */
public class LoginScreen extends javax.swing.JPanel {

    /**
     * Creates new form LoginScreen
     */
    List<User> list;
    JPanel panelRight;
    String clickType;

    public LoginScreen(JPanel panelRight, List<User> list, String clickType) {
        initComponents();
        this.list = list;
        this.panelRight = panelRight;
        this.clickType = clickType;
        initialize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPword = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        txtTitle = new javax.swing.JLabel();
        comboUser = new javax.swing.JComboBox();

        btnSubmit.setText("Login");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        txtTitle.setText("Supplier Login Screen");

        comboUser.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(151, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPword, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTitle)
                            .addComponent(comboUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(btnSubmit)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(txtTitle)
                .addGap(18, 18, 18)
                .addComponent(comboUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSubmit)
                .addContainerGap(199, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        if (comboUser.getSelectedItem() == "Select") {
            JOptionPane.showMessageDialog(null, "Please select a value from the list");
        }
        if (txtPword.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter password");
        }
        String password = txtPword.getText();
        for (User u : list) {
            if (u.getUserName().equalsIgnoreCase(String.valueOf(comboUser.getSelectedItem()))) {
                boolean flag = u.verify(password);
                if (flag) {
                    CardLayout layout = (CardLayout) panelRight.getLayout();
                    SuccessScreen successScreen = new SuccessScreen(u);
                    panelRight.add(successScreen);
                    layout.next(panelRight);
                } else {
                    JOptionPane.showMessageDialog(null, "Wrong Passwrod");
                }
            }
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void initialize() {
        //text should either be "Supplier Login Screen" OR "Customer Login Screen"
        //Based on the selection
        if (clickType.equals("supplier")) {
            txtTitle.setText("Supplier Login Screen");
            for (User u : list) {
                if (u.getRole().equals("SUPPLIER")) {
                    comboUser.addItem(u);
                }
            }
        }
        if (clickType.equals("customer")) {
            txtTitle.setText("Customer Login Screen");
            for (User u : list) {
                if (u.getRole().equals("CUSTOMER")) {
                    comboUser.addItem(u);
                }
            }
        }
        //comboUser.removeAllItems();
        //only customer or suppliers should be listed based on the selection
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox comboUser;
    private javax.swing.JTextField txtPword;
    private javax.swing.JLabel txtTitle;
    // End of variables declaration//GEN-END:variables
}
