/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CustomerInterface;

import Business.CustomerDetails;
import Business.FlightDetails;
import javax.swing.JPanel;

/**
 *
 * @author harry
 */
public class TicketJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BookingJPanel
     */
    private JPanel cardSequencePanel;
    private CustomerDetails cdet;
    private FlightDetails fdet;
    private String s1;

    TicketJPanel(JPanel cardSequencePanel, CustomerDetails cdet, FlightDetails fdet, String s1) {
        initComponents();
        this.cardSequencePanel = cardSequencePanel;
        this.cdet = cdet;
        this.fdet = fdet;
        this.s1 = s1;
        
        nameTF.setText(cdet.getName());
        ageTF.setText(String.valueOf(cdet.getAge()));
        formattedTF.setValue(cdet.getDob());
        
        fromTF.setText(fdet.getFrom());
        toTF.setText(fdet.getTo());
        typeTF.setText(fdet.getType());
        priceTF.setText(String.valueOf(fdet.getPrice()));
        
        populateSeat();
        
    }
    
    public void populateSeat(){
        if (s1.equalsIgnoreCase("Aisle"))
        {
            seatTF.setText("A"+fdet.getA());
        }
        else if (s1.equalsIgnoreCase("Window"))
        {
            seatTF.setText("W"+fdet.getW());
        }
        else if (s1.equalsIgnoreCase("Middle"))
        {
            seatTF.setText("M"+fdet.getM());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        ageLbl = new javax.swing.JLabel();
        ageTF = new javax.swing.JTextField();
        dobLbl = new javax.swing.JLabel();
        seatLbl = new javax.swing.JLabel();
        seatTF = new javax.swing.JTextField();
        exitBtn = new javax.swing.JButton();
        fromLbl = new javax.swing.JLabel();
        fromTF = new javax.swing.JTextField();
        toLbl = new javax.swing.JLabel();
        toTF = new javax.swing.JTextField();
        priceTF = new javax.swing.JTextField();
        priceLbl = new javax.swing.JLabel();
        typeLbl = new javax.swing.JLabel();
        typeTF = new javax.swing.JTextField();
        formattedTF = new javax.swing.JFormattedTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Yay!! Ticket Booked!!");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        nameLbl.setText("Name");
        add(nameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        nameTF.setEditable(false);
        nameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTFActionPerformed(evt);
            }
        });
        add(nameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 90, -1));

        ageLbl.setText("Age");
        add(ageLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        ageTF.setEditable(false);
        ageTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTFActionPerformed(evt);
            }
        });
        add(ageTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 90, -1));

        dobLbl.setText("DOB");
        add(dobLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        seatLbl.setText("Selected Seat");
        add(seatLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        seatTF.setEditable(false);
        seatTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatTFActionPerformed(evt);
            }
        });
        add(seatTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 90, -1));

        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, -1, -1));

        fromLbl.setText("From");
        add(fromLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        fromTF.setEditable(false);
        fromTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromTFActionPerformed(evt);
            }
        });
        add(fromTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 90, -1));

        toLbl.setText("To");
        add(toLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        toTF.setEditable(false);
        toTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toTFActionPerformed(evt);
            }
        });
        add(toTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 90, -1));

        priceTF.setEditable(false);
        priceTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTFActionPerformed(evt);
            }
        });
        add(priceTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 90, -1));

        priceLbl.setText("Price");
        add(priceLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));

        typeLbl.setText("Type");
        add(typeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, -1));

        typeTF.setEditable(false);
        typeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeTFActionPerformed(evt);
            }
        });
        add(typeTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 90, -1));

        formattedTF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        formattedTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formattedTFActionPerformed(evt);
            }
        });
        add(formattedTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 90, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void nameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTFActionPerformed

    private void ageTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTFActionPerformed

    private void seatTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatTFActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void fromTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fromTFActionPerformed

    private void toTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toTFActionPerformed

    private void priceTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTFActionPerformed

    private void typeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeTFActionPerformed

    private void formattedTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formattedTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formattedTFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ageLbl;
    private javax.swing.JTextField ageTF;
    private javax.swing.JLabel dobLbl;
    private javax.swing.JButton exitBtn;
    private javax.swing.JFormattedTextField formattedTF;
    private javax.swing.JLabel fromLbl;
    private javax.swing.JTextField fromTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTF;
    private javax.swing.JLabel priceLbl;
    private javax.swing.JTextField priceTF;
    private javax.swing.JLabel seatLbl;
    private javax.swing.JTextField seatTF;
    private javax.swing.JLabel toLbl;
    private javax.swing.JTextField toTF;
    private javax.swing.JLabel typeLbl;
    private javax.swing.JTextField typeTF;
    // End of variables declaration//GEN-END:variables
}
