/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.VitalSignHistory;
import javax.swing.JOptionPane;

/**
 *
 * @author harry
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private VitalSignHistory vsh;

    public MainJFrame() {
        initComponents();
        vsh = new VitalSignHistory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane = new javax.swing.JSplitPane();
        leftJPanel = new javax.swing.JPanel();
        createBtn = new javax.swing.JButton();
        viewBtn = new javax.swing.JButton();
        maxBPLb = new javax.swing.JLabel();
        minBPLb = new javax.swing.JLabel();
        maxBPTF = new javax.swing.JTextField();
        minBPTF = new javax.swing.JTextField();
        abnormalBtn = new javax.swing.JButton();
        rightJPanel = new javax.swing.JPanel();
        vitalSignLabel = new javax.swing.JLabel();
        vitalSignLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vital SIgns");
        setBackground(new java.awt.Color(255, 255, 204));
        setPreferredSize(new java.awt.Dimension(800, 600));

        jSplitPane.setBackground(new java.awt.Color(255, 255, 204));

        leftJPanel.setBackground(new java.awt.Color(255, 255, 204));

        createBtn.setText("Create Vital Sign");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });

        viewBtn.setText("View Vital Sign");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });

        maxBPLb.setText("Max BP");

        minBPLb.setText("Min BP");

        maxBPTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxBPTFActionPerformed(evt);
            }
        });

        abnormalBtn.setText("Abnormal SIgns");
        abnormalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abnormalBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftJPanelLayout = new javax.swing.GroupLayout(leftJPanel);
        leftJPanel.setLayout(leftJPanelLayout);
        leftJPanelLayout.setHorizontalGroup(
            leftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftJPanelLayout.createSequentialGroup()
                .addGroup(leftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftJPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(leftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createBtn)
                            .addComponent(viewBtn)
                            .addGroup(leftJPanelLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(leftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(leftJPanelLayout.createSequentialGroup()
                                        .addComponent(minBPLb)
                                        .addGap(18, 18, 18)
                                        .addComponent(minBPTF, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(leftJPanelLayout.createSequentialGroup()
                                        .addComponent(maxBPLb)
                                        .addGap(18, 18, 18)
                                        .addComponent(maxBPTF, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(leftJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(abnormalBtn)))
                .addContainerGap())
        );
        leftJPanelLayout.setVerticalGroup(
            leftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftJPanelLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(createBtn)
                .addGap(18, 18, 18)
                .addComponent(viewBtn)
                .addGap(50, 50, 50)
                .addGroup(leftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxBPTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxBPLb))
                .addGap(23, 23, 23)
                .addGroup(leftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minBPLb)
                    .addComponent(minBPTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(abnormalBtn)
                .addContainerGap())
        );

        jSplitPane.setLeftComponent(leftJPanel);

        rightJPanel.setBackground(new java.awt.Color(255, 255, 204));
        rightJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vitalSignLabel.setFont(new java.awt.Font("Rogue Hero 3D", 1, 100)); // NOI18N
        vitalSignLabel.setForeground(new java.awt.Color(0, 102, 255));
        vitalSignLabel.setText("SIGNS");
        rightJPanel.add(vitalSignLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

        vitalSignLabel1.setFont(new java.awt.Font("Rogue Hero 3D", 1, 100)); // NOI18N
        vitalSignLabel1.setForeground(new java.awt.Color(0, 102, 255));
        vitalSignLabel1.setText("VITAL");
        rightJPanel.add(vitalSignLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jSplitPane.setRightComponent(rightJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
        CreateJPanel createPanel = new CreateJPanel(vsh);
        jSplitPane.setRightComponent(createPanel);
    }//GEN-LAST:event_createBtnActionPerformed

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        // TODO add your handling code here:
        ViewJPanel viewPanel = new ViewJPanel(vsh);
        jSplitPane.setRightComponent(viewPanel);
    }//GEN-LAST:event_viewBtnActionPerformed

    private void maxBPTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxBPTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maxBPTFActionPerformed

    private void abnormalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abnormalBtnActionPerformed
        // TODO add your handling code here:
        try {
            double minBP = Double.parseDouble(minBPTF.getText());
            double maxBP = Double.parseDouble(maxBPTF.getText());
            
            if (minBP <= 0 || maxBP <= 0){
                throw new NumberFormatException();
            }

            ViewAbnormalSignsJPanel viewAbnormalPanel = new ViewAbnormalSignsJPanel(vsh, minBP, maxBP);
            jSplitPane.setRightComponent(viewAbnormalPanel);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Enter valid Blood Pressure", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_abnormalBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abnormalBtn;
    private javax.swing.JButton createBtn;
    private javax.swing.JSplitPane jSplitPane;
    private javax.swing.JPanel leftJPanel;
    private javax.swing.JLabel maxBPLb;
    private javax.swing.JTextField maxBPTF;
    private javax.swing.JLabel minBPLb;
    private javax.swing.JTextField minBPTF;
    private javax.swing.JPanel rightJPanel;
    private javax.swing.JButton viewBtn;
    private javax.swing.JLabel vitalSignLabel;
    private javax.swing.JLabel vitalSignLabel1;
    // End of variables declaration//GEN-END:variables
}
