/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.VitalSignHistory;
import Business.VitalSigns;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author harry
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form viewJPanel
     */
    private VitalSignHistory vsh;
    public ViewJPanel(VitalSignHistory vsh) {
        initComponents();
        this.vsh = vsh;
        populateTable();
    }

    public void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel)vitalSignTable.getModel();
        dtm.setRowCount(0);
        
        for(VitalSigns vs : vsh.getVitalSignList()){
            Object row[] = new Object[2];
            row[0] = vs;
            row[1] = vs.getBloodPressure();
            dtm.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tempLb = new javax.swing.JLabel();
        bpTF = new javax.swing.JTextField();
        pulseTF = new javax.swing.JTextField();
        dateLb = new javax.swing.JLabel();
        viewLabel = new javax.swing.JLabel();
        tempTF = new javax.swing.JTextField();
        pulseLb = new javax.swing.JLabel();
        bpLb = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        vitalSignTable = new javax.swing.JTable();
        deleteBtn = new javax.swing.JButton();
        viewDetailsBtn = new javax.swing.JButton();
        dateChooser = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tempLb.setText("Temperature");
        add(tempLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 287, -1, -1));

        bpTF.setEnabled(false);
        add(bpTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 327, 143, -1));

        pulseTF.setEnabled(false);
        add(pulseTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 373, 143, -1));

        dateLb.setText("Date");
        add(dateLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 425, -1, -1));

        viewLabel.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N
        viewLabel.setForeground(new java.awt.Color(255, 51, 51));
        viewLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewLabel.setText("View Vital Sign");
        add(viewLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 22, -1, -1));

        tempTF.setEnabled(false);
        add(tempTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 281, 143, -1));

        pulseLb.setText("Pulse");
        add(pulseLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 379, -1, -1));

        bpLb.setText("Blood Pressure");
        add(bpLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 333, -1, -1));

        vitalSignTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Blood Pressure"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(vitalSignTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 61, 351, 155));

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 234, -1, -1));

        viewDetailsBtn.setText("View Details");
        viewDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDetailsBtnActionPerformed(evt);
            }
        });
        add(viewDetailsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 234, -1, -1));

        dateChooser.setEnabled(false);
        add(dateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 160, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void viewDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailsBtnActionPerformed
        // TODO add your handling code here:
        int selectedrow = vitalSignTable.getSelectedRow();
        
        if(selectedrow >= 0){
            VitalSigns vs = (VitalSigns)vitalSignTable.getValueAt(selectedrow, 0);
            tempTF.setText(String.valueOf(vs.getTemperature()));
            bpTF.setText(String.valueOf(vs.getBloodPressure()));
            pulseTF.setText(String.valueOf(vs.getPulse()));
            //SimpleDateFormat dateFormat = new SimpleDateFormat("mm-dd-yyyy");
            dateChooser.setDate(vs.getDate());
        }
        else {
            JOptionPane.showMessageDialog(null, "No row selected", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_viewDetailsBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        int selectedrow = vitalSignTable.getSelectedRow();
        
        if(selectedrow >= 0){
            VitalSigns vs = (VitalSigns)vitalSignTable.getValueAt(selectedrow, 0);
            int resp = JOptionPane.showConfirmDialog(null, "Do you want to delete this row?", "CONFIRM", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(resp == JOptionPane.YES_OPTION){
                vsh.deleteSign(vs);
                populateTable();
                bpTF.setText("");
                tempTF.setText("");
                pulseTF.setText("");
                dateChooser.setDateFormatString("");
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "No row selected", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_deleteBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bpLb;
    private javax.swing.JTextField bpTF;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JLabel dateLb;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pulseLb;
    private javax.swing.JTextField pulseTF;
    private javax.swing.JLabel tempLb;
    private javax.swing.JTextField tempTF;
    private javax.swing.JButton viewDetailsBtn;
    private javax.swing.JLabel viewLabel;
    private javax.swing.JTable vitalSignTable;
    // End of variables declaration//GEN-END:variables
}
