/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ScheduleInterface;

/**
 *
 * @author harry
 */
public class CreateAirplaneJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateAirplaneJPanel
     */
    public CreateAirplaneJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createAirplaneLbl = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        seatsLbl = new javax.swing.JLabel();
        seatsTF = new javax.swing.JTextField();
        createBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createAirplaneLbl.setText("Create Airlplane");
        add(createAirplaneLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        nameLbl.setText("Name");
        add(nameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, 20));
        add(nameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 120, 30));

        seatsLbl.setText("Number of Seats");
        add(seatsLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, 20));

        seatsTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatsTFActionPerformed(evt);
            }
        });
        add(seatsTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 120, 30));

        createBtn.setText("Create");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });
        add(createBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void seatsTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatsTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatsTFActionPerformed

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel createAirplaneLbl;
    private javax.swing.JButton createBtn;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTF;
    private javax.swing.JLabel seatsLbl;
    private javax.swing.JTextField seatsTF;
    // End of variables declaration//GEN-END:variables
}
