/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ScheduleInterface;

/**
 *
 * @author harry
 */
public class ViewAirplaneJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewAirplaneJPanel
     */
    public ViewAirplaneJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewAirplaneLbl = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        seatsLbl = new javax.swing.JLabel();
        seatsBtn = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewAirplaneLbl.setText("View Airlplane");
        add(viewAirplaneLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        nameLbl.setText("Name");
        add(nameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, 20));
        add(nameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 120, 30));

        seatsLbl.setText("Number of Seats");
        add(seatsLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, 20));

        seatsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatsBtnActionPerformed(evt);
            }
        });
        add(seatsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 120, 30));

        saveBtn.setText("Save");
        saveBtn.setEnabled(false);
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void seatsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatsBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTF;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField seatsBtn;
    private javax.swing.JLabel seatsLbl;
    private javax.swing.JButton updateBtn;
    private javax.swing.JLabel viewAirplaneLbl;
    // End of variables declaration//GEN-END:variables
}
