/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManagerInterface;

import Business.AirlinerDetails;
import Business.AirlinerDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author harry
 */
public class ManageAirlinersJPanel extends javax.swing.JPanel {

    /**
     * Creates new form createAirliner
     */
    private JPanel cardSequencePanel;
    private AirlinerDirectory airDir;

    public ManageAirlinersJPanel(JPanel cardSequencePanel, AirlinerDirectory airDir) {
        initComponents();
        this.airDir = airDir;
        this.cardSequencePanel = cardSequencePanel;
        populate();
    }

    public void populate() {
        DefaultTableModel dtm = (DefaultTableModel) airlinersTable.getModel();
        dtm.setRowCount(0);

        for (AirlinerDetails a : airDir.getAirliner()) {
            Object[] row = new Object[dtm.getColumnCount()];
            row[0] = a;
            row[1] = a.getAddress();
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        airlinersTable = new javax.swing.JTable();
        airlinersLbl = new javax.swing.JLabel();
        viewAirlinerBtn = new javax.swing.JButton();
        createAirlinerBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        airlinersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(airlinersTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 450, 160));

        airlinersLbl.setText("Airliners");
        add(airlinersLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        viewAirlinerBtn.setText("View/Update Airliner");
        viewAirlinerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAirlinerBtnActionPerformed(evt);
            }
        });
        add(viewAirlinerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));

        createAirlinerBtn.setText("Create Airliner");
        createAirlinerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAirlinerBtnActionPerformed(evt);
            }
        });
        add(createAirlinerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, -1, -1));

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void viewAirlinerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAirlinerBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = airlinersTable.getSelectedRow();
        if (selectedRow >= 0) {
            AirlinerDetails air = (AirlinerDetails) airlinersTable.getValueAt(selectedRow, 0);
            ViewAirlinerJPanel viewPanel = new ViewAirlinerJPanel(cardSequencePanel, air, airDir);
            cardSequencePanel.add(viewPanel);
            CardLayout layout = (CardLayout) cardSequencePanel.getLayout();
            layout.next(cardSequencePanel);
        } else {
            JOptionPane.showMessageDialog(null, "Please select a Row!!");
        }
    }//GEN-LAST:event_viewAirlinerBtnActionPerformed

    private void createAirlinerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAirlinerBtnActionPerformed
        // TODO add your handling code here:
        CreateAirlinerJPanel createPanel = new CreateAirlinerJPanel(cardSequencePanel, airDir);
        cardSequencePanel.add(createPanel);
        CardLayout layout = (CardLayout) cardSequencePanel.getLayout();
        layout.next(cardSequencePanel);
    }//GEN-LAST:event_createAirlinerBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = airlinersTable.getSelectedRow();
        if (selectedRow >= 0) {
            int selectionButton = JOptionPane.YES_NO_OPTION;
            int selectionResult = JOptionPane.showConfirmDialog(null, "Are you sure to delete??", "Warning", selectionButton);
            if (selectionResult == JOptionPane.YES_OPTION) {
                AirlinerDetails air = (AirlinerDetails) airlinersTable.getValueAt(selectedRow, 0);
                airDir.removeAirliner(air);
                populate();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a Row!!");
        }
    }//GEN-LAST:event_deleteBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel airlinersLbl;
    private javax.swing.JTable airlinersTable;
    private javax.swing.JButton createAirlinerBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton viewAirlinerBtn;
    // End of variables declaration//GEN-END:variables
}
