/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManagerInterface;

import Business.AirlinerDetails;
import Business.CustomerDetails;
import Business.CustomerDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author harry
 */
public class ShowAllBookings extends javax.swing.JPanel {

    /**
     * Creates new form ShowAllBookings
     */
    private JPanel cardSequencePanel;
    private CustomerDirectory cusDir;
    
    public ShowAllBookings(JPanel cardSequencePanel, CustomerDirectory cusDir) {
        initComponents();
        this.cardSequencePanel = cardSequencePanel;
        this.cusDir = cusDir;
        populate();
    }

    
    public void populate(){
        DefaultTableModel dtm = (DefaultTableModel) bookingTable.getModel();
        dtm.setRowCount(0);

        for (CustomerDetails cd : cusDir.getCustomer()) {
            Object[] row = new Object[dtm.getColumnCount()];
            row[0] = cd;
            row[1] = cd.getAge();
            row[2] = cd.getDob();
            row[3] = cd.getSeat();
            dtm.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        bookingTable = new javax.swing.JTable();
        bookingLbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bookingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Age", "DOB", "Seat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(bookingTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 450, 160));

        bookingLbl.setText("Bookings");
        add(bookingLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        cardSequencePanel.remove(this);
        CardLayout layout = (CardLayout) cardSequencePanel.getLayout();
        layout.previous(cardSequencePanel);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel bookingLbl;
    private javax.swing.JTable bookingTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
