/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.AirlinerDirectory;
import Business.CustomerDirectory;
import CustomerInterface.CustomerBookingJPanel;
import UserInterface.ManagerInterface.ManageAirlinersJPanel;
import UserInterface.ScheduleInterface.AirlinerDetailsJPanel;
import java.awt.CardLayout;

/**
 *
 * @author harry
 */
public class TravelAgencyMain extends javax.swing.JFrame {

    /**
     * Creates new form TravelAgencyMain
     */
    private AirlinerDirectory airDir;
    private CustomerDirectory cusDir;
    
    public TravelAgencyMain() {
        initComponents();
        airDir = new AirlinerDirectory();
        //fliDir = new FlightDirectory();
        cusDir = new CustomerDirectory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        cardSequencePanel = new javax.swing.JPanel();
        controlPanel = new javax.swing.JPanel();
        manageAirlinerBtn = new javax.swing.JButton();
        airlinesBtn = new javax.swing.JButton();
        customerBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));

        cardSequencePanel.setLayout(new java.awt.CardLayout());
        splitPane.setRightComponent(cardSequencePanel);

        controlPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageAirlinerBtn.setText("Manage Airliner");
        manageAirlinerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAirlinerBtnActionPerformed(evt);
            }
        });
        controlPanel.add(manageAirlinerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 42, -1, -1));

        airlinesBtn.setText("Airlines");
        airlinesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airlinesBtnActionPerformed(evt);
            }
        });
        controlPanel.add(airlinesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 89, -1, -1));

        customerBtn.setText("Customer");
        customerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerBtnActionPerformed(evt);
            }
        });
        controlPanel.add(customerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 136, -1, -1));

        splitPane.setLeftComponent(controlPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manageAirlinerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAirlinerBtnActionPerformed
        // TODO add your handling code here:
        ManageAirlinersJPanel manageAirlinersJPanel = new ManageAirlinersJPanel(cardSequencePanel, airDir);
        cardSequencePanel.add(manageAirlinersJPanel);
        CardLayout layout = (CardLayout)cardSequencePanel.getLayout();
        layout.next(cardSequencePanel);
    }//GEN-LAST:event_manageAirlinerBtnActionPerformed

    private void airlinesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airlinesBtnActionPerformed
        // TODO add your handling code here:
        AirlinerDetailsJPanel airlinerDetailsJPanel = new AirlinerDetailsJPanel(cardSequencePanel, airDir);
        cardSequencePanel.add(airlinerDetailsJPanel);
        CardLayout layout = (CardLayout)cardSequencePanel.getLayout();
        layout.next(cardSequencePanel);
    }//GEN-LAST:event_airlinesBtnActionPerformed

    private void customerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerBtnActionPerformed
        // TODO add your handling code here:
        CustomerBookingJPanel customerBooking = new CustomerBookingJPanel(cardSequencePanel, airDir, cusDir);
        cardSequencePanel.add(customerBooking);
        CardLayout layout = (CardLayout)cardSequencePanel.getLayout();
        layout.next(cardSequencePanel);
    }//GEN-LAST:event_customerBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TravelAgencyMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton airlinesBtn;
    private javax.swing.JPanel cardSequencePanel;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JButton customerBtn;
    private javax.swing.JButton manageAirlinerBtn;
    private javax.swing.JSplitPane splitPane;
    // End of variables declaration//GEN-END:variables
}
