/*
 * AdminWorkAreaJPanel.java
 *
 * Created on October 10, 2008, 8:50 AM
 */

package UserInterface.AdminstrativeRole;

import Business.SupplierDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author  Rushabh
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    SupplierDirectory supplierDirectory;
    
    /** Creates new form AdminWorkAreaJPanel */
    public AdminWorkAreaJPanel(JPanel upc, SupplierDirectory sd) {
        initComponents();
        userProcessContainer = upc;
        supplierDirectory = sd;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        managesuppliersButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        managesuppliersButton1.setFont(new java.awt.Font("Tahoma", 0, 18));
        managesuppliersButton1.setText("Manage Suppliers >>");
        managesuppliersButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managesuppliersButton1ActionPerformed(evt);
            }
        });
        add(managesuppliersButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 260, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel1.setText("My Work Area -Aminstrative Role");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void managesuppliersButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managesuppliersButton1ActionPerformed
        // TODO add your handling code here:
        ManageSuppliers panel = new ManageSuppliers(userProcessContainer, supplierDirectory);
        userProcessContainer.add("ManageSupplierAdministrative", panel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_managesuppliersButton1ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton managesuppliersButton1;
    // End of variables declaration//GEN-END:variables
    
}
