/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.ReportPOJO;
import javax.swing.JOptionPane;

/**
 *
 * @author harry
 */
public class AddressPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddressPanel
     */
    
    private ReportPOJO reportPOJO;
    
    public AddressPanel(ReportPOJO reportPOJO) {
        initComponents();
        this.reportPOJO = reportPOJO;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addressDetails = new javax.swing.JLabel();
        street = new javax.swing.JLabel();
        streetTf = new javax.swing.JTextField();
        city = new javax.swing.JLabel();
        state = new javax.swing.JLabel();
        zipcode = new javax.swing.JLabel();
        zipcodeTf = new javax.swing.JTextField();
        stateTf = new javax.swing.JTextField();
        cityTf = new javax.swing.JTextField();
        save = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        addressDetails.setFont(new java.awt.Font("Krungthep", 1, 18)); // NOI18N
        addressDetails.setText("Address Details");

        street.setText("Street");

        streetTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streetTfActionPerformed(evt);
            }
        });

        city.setText("City");

        state.setText("State");

        zipcode.setText("Zipcode");

        stateTf.setText(" ");
        stateTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateTfActionPerformed(evt);
            }
        });

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(save)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(city)
                            .addComponent(street)
                            .addComponent(state)
                            .addComponent(zipcode))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addressDetails)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(streetTf)
                                .addComponent(cityTf)
                                .addComponent(stateTf)
                                .addComponent(zipcodeTf, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(addressDetails)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(street)
                    .addComponent(streetTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(city)
                    .addComponent(cityTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(state)
                    .addComponent(stateTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zipcode)
                    .addComponent(zipcodeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(save)
                .addContainerGap(7, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void streetTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streetTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_streetTfActionPerformed

    private void stateTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stateTfActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        reportPOJO.setStreetAddress(streetTf.getText());
        reportPOJO.setCity(cityTf.getText());
        reportPOJO.setState(stateTf.getText());
        reportPOJO.setZipcode(zipcodeTf.getText());
        
        //promt user for saved data
        JOptionPane.showMessageDialog(null, "Data Saved");
    }//GEN-LAST:event_saveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressDetails;
    private javax.swing.JLabel city;
    private javax.swing.JTextField cityTf;
    private javax.swing.JButton save;
    private javax.swing.JLabel state;
    private javax.swing.JTextField stateTf;
    private javax.swing.JLabel street;
    private javax.swing.JTextField streetTf;
    private javax.swing.JLabel zipcode;
    private javax.swing.JTextField zipcodeTf;
    // End of variables declaration//GEN-END:variables
}
