/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.ReportPOJO;
import javax.swing.JOptionPane;

/**
 *
 * @author harry
 */
public class CheckingPanel extends javax.swing.JPanel {

    /**
     * Creates new form CheckingPanel
     */
    
    private ReportPOJO reportPOJO;
    
    public CheckingPanel(ReportPOJO reportPOJO) {
        initComponents();
        this.reportPOJO = reportPOJO;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkingDetails = new javax.swing.JLabel();
        cbankName = new javax.swing.JLabel();
        cbankNameTf = new javax.swing.JTextField();
        croutingNumTf = new javax.swing.JTextField();
        croutingNum = new javax.swing.JLabel();
        caccountNum = new javax.swing.JLabel();
        caccountNumTf = new javax.swing.JTextField();
        caccountBalanceTf = new javax.swing.JTextField();
        caccountBalance = new javax.swing.JLabel();
        caccountType = new javax.swing.JLabel();
        caccountTypeTf = new javax.swing.JTextField();
        save = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        checkingDetails.setFont(new java.awt.Font("Krungthep", 1, 18)); // NOI18N
        checkingDetails.setText("Checking Bank Account Details");

        cbankName.setText("Bank Name");

        cbankNameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbankNameTfActionPerformed(evt);
            }
        });

        croutingNum.setText("Routing Number");

        caccountNum.setText("Account Number");

        caccountNumTf.setText(" ");
        caccountNumTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caccountNumTfActionPerformed(evt);
            }
        });

        caccountBalance.setText("Account Balance");

        caccountType.setText("Account Type");

        caccountTypeTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caccountTypeTfActionPerformed(evt);
            }
        });

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(save)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbankName)
                                            .addComponent(caccountBalance)
                                            .addComponent(caccountType))
                                        .addGap(21, 21, 21))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(caccountNum)
                                            .addComponent(croutingNum))
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbankNameTf)
                                    .addComponent(croutingNumTf)
                                    .addComponent(caccountNumTf, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                                    .addComponent(caccountBalanceTf)
                                    .addComponent(caccountTypeTf)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(checkingDetails)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(checkingDetails)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbankName)
                    .addComponent(cbankNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(croutingNumTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(croutingNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caccountNumTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caccountNum))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caccountBalance)
                    .addComponent(caccountBalanceTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caccountType, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caccountTypeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(save)
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbankNameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbankNameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbankNameTfActionPerformed

    private void caccountNumTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caccountNumTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caccountNumTfActionPerformed

    private void caccountTypeTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caccountTypeTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caccountTypeTfActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        reportPOJO.setBankNameChecking(cbankNameTf.getText());
        reportPOJO.setRoutingNumberChecking(croutingNumTf.getText());
        reportPOJO.setAccountNumberChecking(caccountNumTf.getText());
        reportPOJO.setBalanceChecking(caccountBalanceTf.getText());
        reportPOJO.setAccountTypeChecking(caccountTypeTf.getText());
        
        //promt user for saved data
        JOptionPane.showMessageDialog(null, "Data Saved");
    }//GEN-LAST:event_saveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel caccountBalance;
    private javax.swing.JTextField caccountBalanceTf;
    private javax.swing.JLabel caccountNum;
    private javax.swing.JTextField caccountNumTf;
    private javax.swing.JLabel caccountType;
    private javax.swing.JTextField caccountTypeTf;
    private javax.swing.JLabel cbankName;
    private javax.swing.JTextField cbankNameTf;
    private javax.swing.JLabel checkingDetails;
    private javax.swing.JLabel croutingNum;
    private javax.swing.JTextField croutingNumTf;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
