/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.ReportPOJO;
import javax.swing.JOptionPane;

/**
 *
 * @author harry
 */
public class DemographyPanel extends javax.swing.JPanel {

    /**
     * Creates new form DemographicInformationPanel
     */
    
    private ReportPOJO reportPOJO;
    
    public DemographyPanel(ReportPOJO reportPOJO) {
        initComponents();
        this.reportPOJO = reportPOJO;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        demographyLabel = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        dobLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        heightLabel = new javax.swing.JLabel();
        weightLabel = new javax.swing.JLabel();
        ssnLabel = new javax.swing.JLabel();
        firstNameTf = new javax.swing.JTextField();
        lastNameTf = new javax.swing.JTextField();
        phoneTf = new javax.swing.JTextField();
        dobTf = new javax.swing.JTextField();
        ageTf = new javax.swing.JTextField();
        heightTf = new javax.swing.JTextField();
        weightTf = new javax.swing.JTextField();
        ssnTf = new javax.swing.JTextField();
        save = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        demographyLabel.setFont(new java.awt.Font("Krungthep", 1, 18)); // NOI18N
        demographyLabel.setText("Demograhic Details");

        firstNameLabel.setText("First Name");

        lastNameLabel.setText("Last Name");

        phoneLabel.setText("Phone Number");

        dobLabel.setText("Date of Birth");

        ageLabel.setText("Age");

        heightLabel.setText("Height");

        weightLabel.setText("Weight");

        ssnLabel.setText("SSN");

        firstNameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTfActionPerformed(evt);
            }
        });

        phoneTf.setText(" ");
        phoneTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneTfActionPerformed(evt);
            }
        });

        ageTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTfActionPerformed(evt);
            }
        });

        heightTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heightTfActionPerformed(evt);
            }
        });

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(ageLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(firstNameLabel)
                                            .addGap(44, 44, 44))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lastNameLabel)
                                            .addGap(18, 18, 18)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(phoneLabel)
                                            .addComponent(dobLabel, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lastNameTf)
                                    .addComponent(firstNameTf)
                                    .addComponent(phoneTf, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                    .addComponent(dobTf)
                                    .addComponent(ageTf)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(heightLabel)
                                    .addComponent(weightLabel)
                                    .addComponent(ssnLabel))
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(heightTf)
                                    .addComponent(weightTf)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(save)
                                        .addGap(0, 105, Short.MAX_VALUE))
                                    .addComponent(ssnTf)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(demographyLabel)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(demographyLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameLabel)
                    .addComponent(lastNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneLabel)
                    .addComponent(phoneTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dobLabel)
                    .addComponent(dobTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ageLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(heightTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(heightLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weightTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weightLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ssnTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ssnLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(save)
                .addContainerGap(10, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTfActionPerformed

    private void phoneTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneTfActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        reportPOJO.setFirstName(firstNameTf.getText());
        reportPOJO.setLastName(lastNameTf.getText());
        reportPOJO.setPhoneNumber(phoneTf.getText());
        reportPOJO.setDob(dobTf.getText());
        reportPOJO.setAge(ageTf.getText());
        reportPOJO.setHeight(heightTf.getText());
        reportPOJO.setWeight(weightTf.getText());
        reportPOJO.setSsn(ssnTf.getText());
        
        //promt user for saved data
        JOptionPane.showMessageDialog(null, "Data Saved");
    }//GEN-LAST:event_saveActionPerformed

    private void ageTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTfActionPerformed

    private void heightTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heightTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heightTfActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField ageTf;
    private javax.swing.JLabel demographyLabel;
    private javax.swing.JLabel dobLabel;
    private javax.swing.JTextField dobTf;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTf;
    private javax.swing.JLabel heightLabel;
    private javax.swing.JTextField heightTf;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTf;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JTextField phoneTf;
    private javax.swing.JButton save;
    private javax.swing.JLabel ssnLabel;
    private javax.swing.JTextField ssnTf;
    private javax.swing.JLabel weightLabel;
    private javax.swing.JTextField weightTf;
    // End of variables declaration//GEN-END:variables
}
