/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.ReportPOJO;

/**
 *
 * @author harry
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    
    private ReportPOJO reportPOJO;
    
    public MainFrame() {
        initComponents();
        reportPOJO = new ReportPOJO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitView = new javax.swing.JSplitPane();
        viewPanel = new javax.swing.JPanel();
        controlPanel = new javax.swing.JPanel();
        demography = new javax.swing.JButton();
        address = new javax.swing.JButton();
        savings = new javax.swing.JButton();
        checking = new javax.swing.JButton();
        license = new javax.swing.JButton();
        medical = new javax.swing.JButton();
        view = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Personal Report Application");
        setPreferredSize(new java.awt.Dimension(1200, 800));

        viewPanel.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout viewPanelLayout = new javax.swing.GroupLayout(viewPanel);
        viewPanel.setLayout(viewPanelLayout);
        viewPanelLayout.setHorizontalGroup(
            viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 375, Short.MAX_VALUE)
        );
        viewPanelLayout.setVerticalGroup(
            viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );

        splitView.setRightComponent(viewPanel);

        controlPanel.setBackground(new java.awt.Color(204, 204, 255));
        controlPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        demography.setText("Demography");
        demography.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                demographyActionPerformed(evt);
            }
        });
        controlPanel.add(demography, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        address.setText("Savings Account");
        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        controlPanel.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 84, -1, -1));

        savings.setText("Address");
        savings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savingsActionPerformed(evt);
            }
        });
        controlPanel.add(savings, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 43, -1, -1));

        checking.setText("Checking Detail");
        checking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkingActionPerformed(evt);
            }
        });
        controlPanel.add(checking, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 125, -1, -1));

        license.setText("Medical Record");
        license.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                licenseActionPerformed(evt);
            }
        });
        controlPanel.add(license, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 202, -1, -1));

        medical.setText("Driving License");
        medical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicalActionPerformed(evt);
            }
        });
        controlPanel.add(medical, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 161, -1, -1));

        view.setText("View");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });
        controlPanel.add(view, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        splitView.setLeftComponent(controlPanel);

        getContentPane().add(splitView, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void demographyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_demographyActionPerformed
        // TODO add your handling code here:
        DemographyPanel demoP = new DemographyPanel(reportPOJO);
        splitView.setRightComponent(demoP);
    }//GEN-LAST:event_demographyActionPerformed

    private void savingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savingsActionPerformed
        // TODO add your handling code here:
        AddressPanel addP = new AddressPanel(reportPOJO);
        splitView.setRightComponent(addP);
    }//GEN-LAST:event_savingsActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
        SavingsPanel savP = new SavingsPanel(reportPOJO);
        splitView.setRightComponent(savP);
    }//GEN-LAST:event_addressActionPerformed

    private void checkingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkingActionPerformed
        // TODO add your handling code here:
        CheckingPanel chkP = new CheckingPanel(reportPOJO);
        splitView.setRightComponent(chkP);
    }//GEN-LAST:event_checkingActionPerformed

    private void medicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicalActionPerformed
        // TODO add your handling code here:
        LicensePanel licP = new LicensePanel(reportPOJO);
        splitView.setRightComponent(licP);
    }//GEN-LAST:event_medicalActionPerformed

    private void licenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_licenseActionPerformed
        // TODO add your handling code here:
        MedicalPanel mdcP = new MedicalPanel(reportPOJO);
        splitView.setRightComponent(mdcP);
    }//GEN-LAST:event_licenseActionPerformed

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        // TODO add your handling code here:
        ViewPanel viewP = new ViewPanel(reportPOJO);
        splitView.setRightComponent(viewP);
    }//GEN-LAST:event_viewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton address;
    private javax.swing.JButton checking;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JButton demography;
    private javax.swing.JButton license;
    private javax.swing.JButton medical;
    private javax.swing.JButton savings;
    private javax.swing.JSplitPane splitView;
    private javax.swing.JButton view;
    private javax.swing.JPanel viewPanel;
    // End of variables declaration//GEN-END:variables
}
