/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.ReportPOJO;
import javax.swing.JOptionPane;

/**
 *
 * @author harry
 */
public class MedicalPanel extends javax.swing.JPanel {

    /**
     * Creates new form MedicalPanel
     */
    
    private ReportPOJO reportPOJO;
    
    public MedicalPanel(ReportPOJO reportPOJO) {
        initComponents();
        this.reportPOJO = reportPOJO;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        medicalRec = new javax.swing.JLabel();
        recNumTf = new javax.swing.JTextField();
        recNum = new javax.swing.JLabel();
        allergy1 = new javax.swing.JLabel();
        allergy2 = new javax.swing.JLabel();
        allergy3 = new javax.swing.JLabel();
        allergy3Tf = new javax.swing.JTextField();
        allergy2Tf = new javax.swing.JTextField();
        allergy1Tf = new javax.swing.JTextField();
        save = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        medicalRec.setFont(new java.awt.Font("Krungthep", 1, 18)); // NOI18N
        medicalRec.setText("Medical Record Details");

        recNumTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recNumTfActionPerformed(evt);
            }
        });

        recNum.setText("Record Number");

        allergy1.setText("Allergy 1");

        allergy2.setText("Allergy 2");

        allergy3.setText("Allergy 3");

        allergy2Tf.setText(" ");
        allergy2Tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allergy2TfActionPerformed(evt);
            }
        });

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(save)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(medicalRec)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(allergy1)
                                .addComponent(recNum)
                                .addComponent(allergy2)
                                .addComponent(allergy3))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(allergy2Tf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                .addComponent(recNumTf, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(allergy1Tf, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(allergy3Tf)))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(medicalRec, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recNum)
                    .addComponent(recNumTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allergy1)
                    .addComponent(allergy1Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allergy2)
                    .addComponent(allergy2Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allergy3)
                    .addComponent(allergy3Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(save)
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void recNumTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recNumTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recNumTfActionPerformed

    private void allergy2TfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allergy2TfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allergy2TfActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        reportPOJO.setMedicalRecordNum(recNumTf.getText());
        reportPOJO.setAllergy1(allergy1Tf.getText());
        reportPOJO.setAllergy2(allergy2Tf.getText());
        reportPOJO.setAllergy3(allergy3Tf.getText());
        
        //promt user for saved data
        JOptionPane.showMessageDialog(null, "Data Saved");
    }//GEN-LAST:event_saveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel allergy1;
    private javax.swing.JTextField allergy1Tf;
    private javax.swing.JLabel allergy2;
    private javax.swing.JTextField allergy2Tf;
    private javax.swing.JLabel allergy3;
    private javax.swing.JTextField allergy3Tf;
    private javax.swing.JLabel medicalRec;
    private javax.swing.JLabel recNum;
    private javax.swing.JTextField recNumTf;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
