/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.ReportPOJO;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author harry
 */
public class ViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form viewPanel
     */
    public ViewPanel(ReportPOJO reportPOJO) {
        initComponents();
        showData(reportPOJO);
    }
    
    private void showData(ReportPOJO reportPOJO){
        
        String firstName = reportPOJO.getFirstName();
        firstNameTf.setText(firstName);
        
        String lastName = reportPOJO.getLastName();
        lastNameTf.setText(lastName);
        
        String phoneNumber = reportPOJO.getPhoneNumber();
        phoneTf.setText(phoneNumber);
        
        String dob = reportPOJO.getDob();
        dobTf.setText(phoneNumber);
        
        String age = reportPOJO.getAge();
        ageTf.setText(dob);
        
        String height = reportPOJO.getHeight();
        heightTf.setText(height);
        
        String weight = reportPOJO.getWeight();
        weigthTf.setText(weight);
        
        String ssn = reportPOJO.getSsn();
        ssnTf.setText(ssn);
        
        String streetAddress = reportPOJO.getStreetAddress();
        streetTf.setText(streetAddress);
        
        String city = reportPOJO.getCity();
        cityTf.setText(city);
        
        String state = reportPOJO.getState();
        stateTf.setText(state);
        
        String zipcode = reportPOJO.getZipcode();
        zipcodeTf.setText(zipcode);
        
        String bankNameSavings = reportPOJO.getBankNameSavings();
        sbankNameTf.setText(bankNameSavings);
        
        String routingNumberSavings = reportPOJO.getRoutingNumberSavings();
        sroutinhNumTf.setText(routingNumberSavings);
        
        String accountNumberSavings = reportPOJO.getAccountNumberSavings();
        saccountNumTf.setText(accountNumberSavings);
        
        String balanceSavings = reportPOJO.getBalanceSavings();
        saccountBalanceTf.setText(balanceSavings);
        
        String accountTypeSavings = reportPOJO.getAccountTypeSavings();
        saccountTypeTf.setText(accountTypeSavings);
        
        String bankNameChecking = reportPOJO.getBankNameChecking();
        cbankNameTf.setText(bankNameChecking);
        
        String routingNumberChecking = reportPOJO.getRoutingNumberChecking();
        croutingNumTf.setText(routingNumberChecking);
        
        String accountNumberChecking = reportPOJO.getAccountNumberChecking();
        caccountNumTf.setText(accountNumberChecking);
        
        String balanceChecking = reportPOJO.getBalanceChecking();
        caccountBalanceTf.setText(balanceChecking);
        
        String accountTypeChecking = reportPOJO.getAccountTypeChecking();
        caccountTypeTf.setText(accountTypeChecking);
        
        String licenseNum = reportPOJO.getLicenseNum();
        licenseNumTf.setText(licenseNum);
        
        String issueDate = reportPOJO.getIssueDate();
        doiTf.setText(issueDate);
        
        String expiryDate = reportPOJO.getExpiryDate();
        doeTf.setText(expiryDate);
        
        String bloodType = reportPOJO.getBloodType();
        bloodTypeTf.setText(bloodType);
        
        String medicalRecordNum = reportPOJO.getMedicalRecordNum();
        recNumTf.setText(medicalRecordNum);
        
        String allergy1 = reportPOJO.getAllergy1();
        allergy1Tf.setText(allergy1);
        
        String allergy2 = reportPOJO.getAllergy2();
        allergy2Tf.setText(allergy2);
        
        String allergy3 = reportPOJO.getAllergy3();
        allergy3Tf.setText(allergy3);
        
        Image snap = new ImageIcon(reportPOJO.getPath()).getImage();
        Image resized = snap.getScaledInstance(100, 100, 100);
        image.setIcon(new ImageIcon(resized));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        personalReport = new javax.swing.JLabel();
        displayArea = new javax.swing.JPanel();
        demoViiew = new javax.swing.JPanel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        dobLabel = new javax.swing.JLabel();
        ssnLabel = new javax.swing.JLabel();
        weightLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        heightLabel = new javax.swing.JLabel();
        ageTf = new javax.swing.JTextField();
        firstNameTf = new javax.swing.JTextField();
        lastNameTf = new javax.swing.JTextField();
        phoneTf = new javax.swing.JTextField();
        dobTf = new javax.swing.JTextField();
        ssnTf = new javax.swing.JTextField();
        weigthTf = new javax.swing.JTextField();
        heightTf = new javax.swing.JTextField();
        demographyLabel = new javax.swing.JLabel();
        addressView = new javax.swing.JPanel();
        street = new javax.swing.JLabel();
        city = new javax.swing.JLabel();
        state = new javax.swing.JLabel();
        zipcode = new javax.swing.JLabel();
        streetTf = new javax.swing.JTextField();
        cityTf = new javax.swing.JTextField();
        stateTf = new javax.swing.JTextField();
        zipcodeTf = new javax.swing.JTextField();
        addressDetails = new javax.swing.JLabel();
        savingsView = new javax.swing.JPanel();
        savingsDetails = new javax.swing.JLabel();
        sbankName = new javax.swing.JLabel();
        sbankNameTf = new javax.swing.JTextField();
        sroutinhNumTf = new javax.swing.JTextField();
        sroutingNum = new javax.swing.JLabel();
        saccountNum = new javax.swing.JLabel();
        saccountNumTf = new javax.swing.JTextField();
        saccountBalanceTf = new javax.swing.JTextField();
        saccountBalance = new javax.swing.JLabel();
        saccountType = new javax.swing.JLabel();
        saccountTypeTf = new javax.swing.JTextField();
        checkingView = new javax.swing.JPanel();
        checkingDetails = new javax.swing.JLabel();
        cbankName = new javax.swing.JLabel();
        cbankNameTf = new javax.swing.JTextField();
        croutingNumTf = new javax.swing.JTextField();
        caccountNumTf = new javax.swing.JTextField();
        caccountNum = new javax.swing.JLabel();
        croutingNum = new javax.swing.JLabel();
        caccountBalance = new javax.swing.JLabel();
        caccountType = new javax.swing.JLabel();
        caccountTypeTf = new javax.swing.JTextField();
        caccountBalanceTf = new javax.swing.JTextField();
        licenseView = new javax.swing.JPanel();
        bloodTypeTf = new javax.swing.JTextField();
        bloodType = new javax.swing.JLabel();
        doiTf = new javax.swing.JTextField();
        doi = new javax.swing.JLabel();
        doe = new javax.swing.JLabel();
        doeTf = new javax.swing.JTextField();
        licenseDetails = new javax.swing.JLabel();
        licenseNumTf = new javax.swing.JTextField();
        licenseNum = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        medicalView = new javax.swing.JPanel();
        medicalRec = new javax.swing.JLabel();
        recNumTf = new javax.swing.JTextField();
        allergy2 = new javax.swing.JLabel();
        allergy3 = new javax.swing.JLabel();
        recNum = new javax.swing.JLabel();
        allergy1 = new javax.swing.JLabel();
        allergy1Tf = new javax.swing.JTextField();
        allergy3Tf = new javax.swing.JTextField();
        allergy2Tf = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 255, 204));
        setLayout(new java.awt.BorderLayout());

        personalReport.setFont(new java.awt.Font("Orbitron", 1, 22)); // NOI18N
        personalReport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        personalReport.setText("Personal Report");
        add(personalReport, java.awt.BorderLayout.PAGE_START);

        displayArea.setBackground(new java.awt.Color(204, 255, 204));
        displayArea.setLayout(new java.awt.GridLayout(3, 2));

        demoViiew.setBackground(new java.awt.Color(204, 255, 204));

        firstNameLabel.setText("First Name");

        lastNameLabel.setText("Last Name");

        phoneLabel.setText("Phone Number");

        dobLabel.setText("Date of Birth");

        ssnLabel.setText("SSN");

        weightLabel.setText("Weight");

        ageLabel.setText("Age");

        heightLabel.setText("Height");

        ageTf.setEditable(false);

        firstNameTf.setEditable(false);
        firstNameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTfActionPerformed(evt);
            }
        });

        lastNameTf.setEditable(false);

        phoneTf.setEditable(false);
        phoneTf.setText(" ");
        phoneTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneTfActionPerformed(evt);
            }
        });

        dobTf.setEditable(false);

        ssnTf.setEditable(false);
        ssnTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssnTfActionPerformed(evt);
            }
        });

        weigthTf.setEditable(false);
        weigthTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weigthTfActionPerformed(evt);
            }
        });

        heightTf.setEditable(false);
        heightTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heightTfActionPerformed(evt);
            }
        });

        demographyLabel.setFont(new java.awt.Font("Mshtakan", 1, 18)); // NOI18N
        demographyLabel.setText("Demograhic Details");

        javax.swing.GroupLayout demoViiewLayout = new javax.swing.GroupLayout(demoViiew);
        demoViiew.setLayout(demoViiewLayout);
        demoViiewLayout.setHorizontalGroup(
            demoViiewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(demoViiewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(demoViiewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(demographyLabel)
                    .addGroup(demoViiewLayout.createSequentialGroup()
                        .addGroup(demoViiewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastNameLabel)
                            .addComponent(firstNameLabel)
                            .addComponent(phoneLabel)
                            .addComponent(dobLabel))
                        .addGap(18, 18, 18)
                        .addGroup(demoViiewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(dobTf, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phoneTf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(lastNameTf, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstNameTf, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(demoViiewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(weightLabel)
                            .addGroup(demoViiewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(demoViiewLayout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addGroup(demoViiewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ageLabel)
                                        .addComponent(heightLabel)))
                                .addComponent(ssnLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(demoViiewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(heightTf, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(ageTf)
                            .addComponent(weigthTf)
                            .addComponent(ssnTf))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        demoViiewLayout.setVerticalGroup(
            demoViiewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(demoViiewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(demographyLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(demoViiewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(demoViiewLayout.createSequentialGroup()
                        .addGroup(demoViiewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(demoViiewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(firstNameLabel)
                                .addComponent(firstNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(demoViiewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastNameLabel)
                            .addComponent(heightLabel)
                            .addComponent(heightTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(ageTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(demoViiewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneLabel)
                    .addComponent(weightLabel)
                    .addComponent(weigthTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(demoViiewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dobLabel)
                    .addComponent(dobTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ssnLabel)
                    .addComponent(ssnTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(158, Short.MAX_VALUE))
        );

        displayArea.add(demoViiew);

        addressView.setBackground(new java.awt.Color(204, 255, 204));

        street.setText("Street");

        city.setText("City");

        state.setText("State");

        zipcode.setText("Zipcode");

        streetTf.setEditable(false);
        streetTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streetTfActionPerformed(evt);
            }
        });

        cityTf.setEditable(false);

        stateTf.setEditable(false);
        stateTf.setText(" ");
        stateTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateTfActionPerformed(evt);
            }
        });

        zipcodeTf.setEditable(false);

        addressDetails.setFont(new java.awt.Font("Mshtakan", 1, 18)); // NOI18N
        addressDetails.setText("Address Details");

        javax.swing.GroupLayout addressViewLayout = new javax.swing.GroupLayout(addressView);
        addressView.setLayout(addressViewLayout);
        addressViewLayout.setHorizontalGroup(
            addressViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addressViewLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(addressViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addressDetails)
                    .addGroup(addressViewLayout.createSequentialGroup()
                        .addGroup(addressViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(city)
                            .addComponent(street)
                            .addComponent(state)
                            .addComponent(zipcode))
                        .addGap(18, 18, 18)
                        .addGroup(addressViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(streetTf)
                            .addComponent(cityTf)
                            .addComponent(stateTf)
                            .addComponent(zipcodeTf, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        addressViewLayout.setVerticalGroup(
            addressViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addressViewLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(addressDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addressViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(street)
                    .addComponent(streetTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addressViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(city)
                    .addComponent(cityTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addressViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(state)
                    .addComponent(stateTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addressViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zipcode)
                    .addComponent(zipcodeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(127, Short.MAX_VALUE))
        );

        displayArea.add(addressView);

        savingsView.setBackground(new java.awt.Color(204, 255, 204));

        savingsDetails.setFont(new java.awt.Font("Mshtakan", 1, 18)); // NOI18N
        savingsDetails.setText("Savings Bank Account Details");

        sbankName.setText("Bank Name");

        sbankNameTf.setEditable(false);
        sbankNameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbankNameTfActionPerformed(evt);
            }
        });

        sroutinhNumTf.setEditable(false);

        sroutingNum.setText("Routing Number");

        saccountNum.setText("Account Number");

        saccountNumTf.setEditable(false);
        saccountNumTf.setText(" ");
        saccountNumTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saccountNumTfActionPerformed(evt);
            }
        });

        saccountBalanceTf.setEditable(false);

        saccountBalance.setText("Account Balance");

        saccountType.setText("Account Type");

        saccountTypeTf.setEditable(false);
        saccountTypeTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saccountTypeTfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout savingsViewLayout = new javax.swing.GroupLayout(savingsView);
        savingsView.setLayout(savingsViewLayout);
        savingsViewLayout.setHorizontalGroup(
            savingsViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(savingsViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(savingsViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(savingsDetails)
                    .addGroup(savingsViewLayout.createSequentialGroup()
                        .addGroup(savingsViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(savingsViewLayout.createSequentialGroup()
                                .addGroup(savingsViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sbankName)
                                    .addComponent(saccountBalance)
                                    .addComponent(saccountType))
                                .addGap(21, 21, 21))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, savingsViewLayout.createSequentialGroup()
                                .addGroup(savingsViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(saccountNum)
                                    .addComponent(sroutingNum))
                                .addGap(18, 18, 18)))
                        .addGroup(savingsViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sbankNameTf)
                            .addComponent(sroutinhNumTf)
                            .addComponent(saccountNumTf)
                            .addComponent(saccountBalanceTf)
                            .addComponent(saccountTypeTf, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        savingsViewLayout.setVerticalGroup(
            savingsViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(savingsViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(savingsDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(savingsViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sbankName)
                    .addComponent(sbankNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(savingsViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sroutinhNumTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sroutingNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(savingsViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saccountNumTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saccountNum))
                .addGap(12, 12, 12)
                .addGroup(savingsViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saccountBalance)
                    .addComponent(saccountBalanceTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(savingsViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saccountType, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saccountTypeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        displayArea.add(savingsView);

        checkingView.setBackground(new java.awt.Color(204, 255, 204));

        checkingDetails.setFont(new java.awt.Font("Mshtakan", 1, 18)); // NOI18N
        checkingDetails.setText("Checking Bank Account Details");

        cbankName.setText("Bank Name");

        cbankNameTf.setEditable(false);
        cbankNameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbankNameTfActionPerformed(evt);
            }
        });

        croutingNumTf.setEditable(false);

        caccountNumTf.setEditable(false);
        caccountNumTf.setText(" ");
        caccountNumTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caccountNumTfActionPerformed(evt);
            }
        });

        caccountNum.setText("Account Number");

        croutingNum.setText("Routing Number");

        caccountBalance.setText("Account Balance");

        caccountType.setText("Account Type");

        caccountTypeTf.setEditable(false);
        caccountTypeTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caccountTypeTfActionPerformed(evt);
            }
        });

        caccountBalanceTf.setEditable(false);

        javax.swing.GroupLayout checkingViewLayout = new javax.swing.GroupLayout(checkingView);
        checkingView.setLayout(checkingViewLayout);
        checkingViewLayout.setHorizontalGroup(
            checkingViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkingViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(checkingViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkingDetails)
                    .addGroup(checkingViewLayout.createSequentialGroup()
                        .addGroup(checkingViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(checkingViewLayout.createSequentialGroup()
                                .addGroup(checkingViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbankName)
                                    .addComponent(caccountBalance)
                                    .addComponent(caccountType))
                                .addGap(21, 21, 21))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkingViewLayout.createSequentialGroup()
                                .addGroup(checkingViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(caccountNum)
                                    .addComponent(croutingNum))
                                .addGap(18, 18, 18)))
                        .addGroup(checkingViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbankNameTf)
                            .addComponent(croutingNumTf)
                            .addComponent(caccountNumTf)
                            .addComponent(caccountBalanceTf)
                            .addComponent(caccountTypeTf, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        checkingViewLayout.setVerticalGroup(
            checkingViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkingViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkingDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(checkingViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbankName)
                    .addComponent(cbankNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(checkingViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(croutingNumTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(croutingNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(checkingViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caccountNumTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caccountNum))
                .addGap(12, 12, 12)
                .addGroup(checkingViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caccountBalance)
                    .addComponent(caccountBalanceTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(checkingViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caccountType, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caccountTypeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        displayArea.add(checkingView);

        licenseView.setBackground(new java.awt.Color(204, 255, 204));

        bloodTypeTf.setEditable(false);

        bloodType.setText("Blood Type");

        doiTf.setEditable(false);

        doi.setText("Date of Issue");

        doe.setText("Date of Expiry");

        doeTf.setEditable(false);
        doeTf.setText(" ");
        doeTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doeTfActionPerformed(evt);
            }
        });

        licenseDetails.setFont(new java.awt.Font("Mshtakan", 1, 18)); // NOI18N
        licenseDetails.setText("Driving License Details");

        licenseNumTf.setEditable(false);
        licenseNumTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                licenseNumTfActionPerformed(evt);
            }
        });

        licenseNum.setText("License Number");

        javax.swing.GroupLayout licenseViewLayout = new javax.swing.GroupLayout(licenseView);
        licenseView.setLayout(licenseViewLayout);
        licenseViewLayout.setHorizontalGroup(
            licenseViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(licenseViewLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(licenseViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(licenseViewLayout.createSequentialGroup()
                        .addGroup(licenseViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(licenseViewLayout.createSequentialGroup()
                                .addGroup(licenseViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bloodType)
                                    .addGroup(licenseViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(doe, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(doi)))
                                .addGap(30, 30, 30))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, licenseViewLayout.createSequentialGroup()
                                .addComponent(licenseNum)
                                .addGap(18, 18, 18)))
                        .addGroup(licenseViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(licenseNumTf)
                            .addComponent(doiTf)
                            .addComponent(doeTf, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(bloodTypeTf))
                        .addGap(26, 26, 26)
                        .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(licenseDetails))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        licenseViewLayout.setVerticalGroup(
            licenseViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(licenseViewLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(licenseDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(licenseViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(licenseNum)
                    .addComponent(licenseNumTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(licenseViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doiTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(licenseViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doe))
                .addGap(9, 9, 9)
                .addGroup(licenseViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bloodTypeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bloodType))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, licenseViewLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        displayArea.add(licenseView);

        medicalView.setBackground(new java.awt.Color(204, 255, 204));

        medicalRec.setFont(new java.awt.Font("Mshtakan", 1, 18)); // NOI18N
        medicalRec.setText("Medical Record Details");

        recNumTf.setEditable(false);
        recNumTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recNumTfActionPerformed(evt);
            }
        });

        allergy2.setText("Allergy 2");

        allergy3.setText("Allergy 3");

        recNum.setText("Record Number");

        allergy1.setText("Allergy 1");

        allergy1Tf.setEditable(false);

        allergy3Tf.setEditable(false);

        allergy2Tf.setEditable(false);
        allergy2Tf.setText(" ");
        allergy2Tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allergy2TfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout medicalViewLayout = new javax.swing.GroupLayout(medicalView);
        medicalView.setLayout(medicalViewLayout);
        medicalViewLayout.setHorizontalGroup(
            medicalViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(medicalViewLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(medicalViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(medicalRec)
                    .addGroup(medicalViewLayout.createSequentialGroup()
                        .addGroup(medicalViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(allergy1)
                            .addComponent(recNum)
                            .addComponent(allergy2)
                            .addComponent(allergy3))
                        .addGap(18, 18, 18)
                        .addGroup(medicalViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(allergy3Tf, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(allergy1Tf, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(allergy2Tf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addComponent(recNumTf))))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        medicalViewLayout.setVerticalGroup(
            medicalViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(medicalViewLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(medicalRec, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(medicalViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recNum)
                    .addComponent(recNumTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(medicalViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allergy1)
                    .addComponent(allergy1Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(medicalViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allergy2)
                    .addComponent(allergy2Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(medicalViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allergy3)
                    .addComponent(allergy3Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(135, Short.MAX_VALUE))
        );

        displayArea.add(medicalView);

        add(displayArea, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void sbankNameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbankNameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sbankNameTfActionPerformed

    private void saccountNumTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saccountNumTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saccountNumTfActionPerformed

    private void saccountTypeTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saccountTypeTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saccountTypeTfActionPerformed

    private void firstNameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTfActionPerformed

    private void phoneTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneTfActionPerformed

    private void streetTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streetTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_streetTfActionPerformed

    private void stateTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stateTfActionPerformed

    private void cbankNameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbankNameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbankNameTfActionPerformed

    private void caccountNumTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caccountNumTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caccountNumTfActionPerformed

    private void caccountTypeTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caccountTypeTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caccountTypeTfActionPerformed

    private void doeTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doeTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doeTfActionPerformed

    private void licenseNumTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_licenseNumTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_licenseNumTfActionPerformed

    private void recNumTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recNumTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recNumTfActionPerformed

    private void allergy2TfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allergy2TfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allergy2TfActionPerformed

    private void heightTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heightTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heightTfActionPerformed

    private void weigthTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weigthTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weigthTfActionPerformed

    private void ssnTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssnTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ssnTfActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressDetails;
    private javax.swing.JPanel addressView;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField ageTf;
    private javax.swing.JLabel allergy1;
    private javax.swing.JTextField allergy1Tf;
    private javax.swing.JLabel allergy2;
    private javax.swing.JTextField allergy2Tf;
    private javax.swing.JLabel allergy3;
    private javax.swing.JTextField allergy3Tf;
    private javax.swing.JLabel bloodType;
    private javax.swing.JTextField bloodTypeTf;
    private javax.swing.JLabel caccountBalance;
    private javax.swing.JTextField caccountBalanceTf;
    private javax.swing.JLabel caccountNum;
    private javax.swing.JTextField caccountNumTf;
    private javax.swing.JLabel caccountType;
    private javax.swing.JTextField caccountTypeTf;
    private javax.swing.JLabel cbankName;
    private javax.swing.JTextField cbankNameTf;
    private javax.swing.JLabel checkingDetails;
    private javax.swing.JPanel checkingView;
    private javax.swing.JLabel city;
    private javax.swing.JTextField cityTf;
    private javax.swing.JLabel croutingNum;
    private javax.swing.JTextField croutingNumTf;
    private javax.swing.JPanel demoViiew;
    private javax.swing.JLabel demographyLabel;
    private javax.swing.JPanel displayArea;
    private javax.swing.JLabel dobLabel;
    private javax.swing.JTextField dobTf;
    private javax.swing.JLabel doe;
    private javax.swing.JTextField doeTf;
    private javax.swing.JLabel doi;
    private javax.swing.JTextField doiTf;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTf;
    private javax.swing.JLabel heightLabel;
    private javax.swing.JTextField heightTf;
    private javax.swing.JLabel image;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTf;
    private javax.swing.JLabel licenseDetails;
    private javax.swing.JLabel licenseNum;
    private javax.swing.JTextField licenseNumTf;
    private javax.swing.JPanel licenseView;
    private javax.swing.JLabel medicalRec;
    private javax.swing.JPanel medicalView;
    private javax.swing.JLabel personalReport;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JTextField phoneTf;
    private javax.swing.JLabel recNum;
    private javax.swing.JTextField recNumTf;
    private javax.swing.JLabel saccountBalance;
    private javax.swing.JTextField saccountBalanceTf;
    private javax.swing.JLabel saccountNum;
    private javax.swing.JTextField saccountNumTf;
    private javax.swing.JLabel saccountType;
    private javax.swing.JTextField saccountTypeTf;
    private javax.swing.JLabel savingsDetails;
    private javax.swing.JPanel savingsView;
    private javax.swing.JLabel sbankName;
    private javax.swing.JTextField sbankNameTf;
    private javax.swing.JLabel sroutingNum;
    private javax.swing.JTextField sroutinhNumTf;
    private javax.swing.JLabel ssnLabel;
    private javax.swing.JTextField ssnTf;
    private javax.swing.JLabel state;
    private javax.swing.JTextField stateTf;
    private javax.swing.JLabel street;
    private javax.swing.JTextField streetTf;
    private javax.swing.JLabel weightLabel;
    private javax.swing.JTextField weigthTf;
    private javax.swing.JLabel zipcode;
    private javax.swing.JTextField zipcodeTf;
    // End of variables declaration//GEN-END:variables
}
